// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ASP_NET_Core_Web_API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260901071640_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DeliveryTime")
                        .HasColumnType("int")
                        .HasColumnName("delivery_time");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("image");

                    b.Property<int>("ImageVersion")
                        .HasColumnType("int")
                        .HasColumnName("image_version");

                    b.Property<string>("LongDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("long_description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<double>("Price")
                        .HasColumnType("float")
                        .HasColumnName("price");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("short_description");

                    b.HasKey("Id");

                    b.ToTable("menu", null, t =>
                        {
                            t.HasCheckConstraint("CK_menu_id_positive", "id > 0");

                            t.HasCheckConstraint("CK_menu_image_version_positive", "image_version >= 0");

                            t.HasCheckConstraint("CK_menu_lat_range", "location_lat BETWEEN -90 AND 90");

                            t.HasCheckConstraint("CK_menu_lng_range", "location_lng BETWEEN -180 AND 180");

                            t.HasCheckConstraint("CK_menu_price_positive", "price >= 0");
                        });
                });

            modelBuilder.Entity("Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreationTimestamp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("creation_timestamp");

                    b.Property<string>("DeliveryTimestamp")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("delivery_timestamp");

                    b.Property<int>("Mid")
                        .HasColumnType("int")
                        .HasColumnName("menu_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.Property<int>("Uid")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("Mid");

                    b.HasIndex("Uid");

                    b.ToTable("order", null, t =>
                        {
                            t.HasCheckConstraint("CK_order_delivery_after_creation", "delivery_timestamp >= creation_timestamp");

                            t.HasCheckConstraint("CK_order_delivery_timestamp_logic", "(status = 'ON_DELIVERY' AND delivery_timestamp IS NULL) OR (status = 'COMPLETED' AND delivery_timestamp IS NOT NULL)");

                            t.HasCheckConstraint("CK_order_id_positive", "id > 0");

                            t.HasCheckConstraint("CK_order_lat_range", "current_position_lat BETWEEN -90 AND 90");

                            t.HasCheckConstraint("CK_order_lng_range", "current_position_lng BETWEEN -180 AND 180");

                            t.HasCheckConstraint("CK_order_menu_id_positive", "menu_id > 0");

                            t.HasCheckConstraint("CK_order_status_valid", "status IN ('ON_DELIVERY', 'COMPLETED')");

                            t.HasCheckConstraint("CK_order_user_id_positive", "user_id > 0");
                        });
                });

            modelBuilder.Entity("UidSid", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("id");

                    b.Property<int>("Uid")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("Uid");

                    b.ToTable("uid_sid", null, t =>
                        {
                            t.HasCheckConstraint("CK_uid_sid_user_id_positive", "user_id >= 0");
                        });
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CardCVV")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("card_cvv");

                    b.Property<int?>("CardExpireMonth")
                        .HasColumnType("int")
                        .HasColumnName("card_expire_month");

                    b.Property<int?>("CardExpireYear")
                        .HasColumnType("int")
                        .HasColumnName("card_expire_year");

                    b.Property<string>("CardFullName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("card_full_name");

                    b.Property<string>("CardNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("card_number");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("last_name");

                    b.HasKey("Id");

                    b.ToTable("user", null, t =>
                        {
                            t.HasCheckConstraint("CK_user_card_expire_month", "card_expire_month BETWEEN 1 AND 12");

                            t.HasCheckConstraint("CK_user_id_positive", "id > 0");
                        });
                });

            modelBuilder.Entity("Menu", b =>
                {
                    b.OwnsOne("Location", "Location", b1 =>
                        {
                            b1.Property<int>("MenuId")
                                .HasColumnType("int");

                            b1.Property<float>("Lat")
                                .HasColumnType("real")
                                .HasColumnName("location_lat");

                            b1.Property<float>("Lng")
                                .HasColumnType("real")
                                .HasColumnName("location_lng");

                            b1.HasKey("MenuId");

                            b1.ToTable("menu");

                            b1.WithOwner()
                                .HasForeignKey("MenuId");
                        });

                    b.Navigation("Location")
                        .IsRequired();
                });

            modelBuilder.Entity("Order", b =>
                {
                    b.HasOne("Menu", "Menu")
                        .WithMany()
                        .HasForeignKey("Mid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("User", "User")
                        .WithMany()
                        .HasForeignKey("Uid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Location", "CurrentPosition", b1 =>
                        {
                            b1.Property<int>("OrderId")
                                .HasColumnType("int");

                            b1.Property<float>("Lat")
                                .HasColumnType("real")
                                .HasColumnName("current_position_lat");

                            b1.Property<float>("Lng")
                                .HasColumnType("real")
                                .HasColumnName("current_position_lng");

                            b1.HasKey("OrderId");

                            b1.ToTable("order");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");
                        });

                    b.Navigation("CurrentPosition")
                        .IsRequired();

                    b.Navigation("Menu");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UidSid", b =>
                {
                    b.HasOne("User", "User")
                        .WithMany()
                        .HasForeignKey("Uid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
